name: Continous
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.3
        with:
          linter: flake8

    #DISCORD:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run Discord Notify action
          uses: PingChunChung/actions-discord-notifier
          with:
            webhook_url:  ${{ secrets.DISCORD_WEBHOOKS_URL }}